This notebook contains work from the Linear Algrebra Assessment

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],[2,7,4]])
print(A)

[[1 2 3]
 [2 7 4]]


In [3]:
A.shape

(2, 3)

In [4]:
B=np.array([1,8,0,5])
print(B.shape)
print(B.shape)

(4,)
(4,)


In [5]:
print(np.transpose(B))
print(np.transpose(B).shape)

[1 8 0 5]
(4,)


In [6]:
C=np.array([[0,1],[1,2]])

In [7]:
print(C)
print(np.transpose(C))

[[0 1]
 [1 2]]
[[0 1]
 [1 2]]


In [8]:
D=np.matrix('1;8;0;5')

In [9]:
print(D)
print(D.shape)

[[1]
 [8]
 [0]
 [5]]
(4, 1)


In [10]:
u=np.array([6, 2, -3, 5])

In [11]:
print(u)
print(u.shape)

[ 6  2 -3  5]
(4,)


In [12]:
print(np.ones((1,4)))

[[1. 1. 1. 1.]]


In [13]:
u=np.array([6,2,-3,5])
v=np.array([3,5,-1,4])
print(u+v)

[ 9  7 -4  9]


In [14]:
print(u-v)

[ 3 -3 -2  1]


In [15]:
print(A)

[[1 2 3]
 [2 7 4]]


In [16]:
np.dot(u,v)

51

In [17]:
np.linalg.norm(u)

8.602325267042627

In [18]:
print(A)

[[1 2 3]
 [2 7 4]]


In [19]:
C=np.array([[5,-1],[9,1],[6,0]])
print(C)

[[ 5 -1]
 [ 9  1]
 [ 6  0]]


In [20]:
print(A-np.transpose(C))

[[-4 -7 -3]
 [ 3  6  4]]


In [21]:
D=np.array([[3,-2,-1],[1,2,3]])
print(D)

[[ 3 -2 -1]
 [ 1  2  3]]


In [22]:
print(np.transpose(C)+3*D)

[[14  3  3]
 [ 2  7  9]]


In [23]:
print(A)
B=np.array([[1,-1],[0,1]])
print(B)
np.matmul(B,A)

[[1 2 3]
 [2 7 4]]
[[ 1 -1]
 [ 0  1]]


array([[-1, -5, -1],
       [ 2,  7,  4]])

In [24]:
print(B)
print(np.transpose(A))
np.matmul(B,np.transpose(A))

[[ 1 -1]
 [ 0  1]]
[[1 2]
 [2 7]
 [3 4]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [25]:
print(np.matmul(B,A))
print(B @ np.transpose(A))

[[-1 -5 -1]
 [ 2  7  4]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [26]:
np.linalg.matrix_power(B, 4)

array([[ 1, -4],
       [ 0,  1]])

In [27]:
# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape, 
    'B': B.shape, 
    'C': C.shape, 
    'D': D.shape, 
    'u': u.shape, 
    'v': v.shape
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = u+v            # u+v
u_minus_v = u-v           # u-v
alpha_times_u = 6*u       # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)              # u . v
norm_u = np.linalg.norm(u)              # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None             # A + C
A_minus_Ctranspose = A-np.transpose(C)   # A - C.T
Ctranspose_plus_3D = np.transpose(C)+3*D   # C.T + 3*D
B_times_A = np.matmul(B,A)            # B*A
B_times_Atranspose = None   # B*A.T

# Q4: (bonus)

B_times_C = None             # B*C
C_times_B = np.matmul(C,B)             # C*B
B_exp_4 = np.linalg.matrix_power(B, 4)               # B^4
A_times_Atranspose = np.matmul(A,np.transpose(A))    # A*A.T
Dtranspose_times_D = np.dot(np.transpose(D),D)    # D.T*D

In [28]:
B_times_A

array([[-1, -5, -1],
       [ 2,  7,  4]])